### ISSUE TITLE
Can not preview the Country Code Picker.

### ISSUE THREAD

**Issue by morarafrank** [joelkanyi/kompose-country-code-picker#37]
![Kccp](https://github.com/joelkanyi/KomposeCountryCodePicker/assets/86305645/7dfb0a13-2cf5-4379-b47a-4bb7d7929e57)

**Comment by morarafrank** [comment]
java.lang.AssertionError: Unsupported Service: phone

**Comment by joelkanyi** [comment]
Thank you for reporting the issue, can you share a reproducible sample

**Comment by joelkanyi** [comment]
@morarafrank no need of sharing a sample, the issue is with compose previews and I have reported the issue to Google, lets see how it goes:

https://issuetracker.google.com/u/1/issues/333219064

**Comment by joelkanyi** [comment]
Hey @morarafrank because we cannot use `TelephonyManager` on preview, with the latest version of the library, on your preview just a default country code, it should work.

Example:
```kotlin
@Preview
@Composable
private fun Preview() {
    ComposePickerTheme {
        val state = rememberKomposeCountryCodePickerState(
            defaultCountryCode = "ke",
        )
        KomposeCountryCodePicker(
            modifier = Modifier.fillMaxWidth(),
            text = "",
            onValueChange = {},
            state = state,
        )
    }
}
```

<img width="447" alt="Screenshot 2024-06-08 at 20 51 35" src="https://github.com/joelkanyi/kompose-country-code-picker/assets/50293753/2cb3f7a7-d0f7-4337-8a08-cd7109a29dff">
